# WhatATheme
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: False
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: bash
    span: false
# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Mahra Rahimi
# Description of the Site
description: Developer Blog
# URL of Image of the Site
site-image: /assets/images/meta.jpg
# Keywords of the Site
site-keywords: Blog, Tech, Develop
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/bg.jpeg
#roll192_003.jpg
# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: mahra.rah@gmail.com
facebook_username:
twitter_username:
instagram_username:
linkedin_username: 
github_username:  MahrRah
youtube_channel_id:


# # Google Analytics
# google-analytics: UA-163806439-1

# # Disqus
# disqus-shortname: thedevslot

# Name of the Author
author-name: Mahra Rahimi
# URL for the Image of the Author
author-image: /assets/images/author-image.jpg
# 60 Words About the Author
author-about: I am Mahra a Software Engineer at Microsoft with a background in astrophysics. A physics nerd who has lost her way in the world of tech. 
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/MahrRah

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
